// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abtlmqbahlnxnelzkvfx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFidGxtcWJhaGxueG5lbHprdmZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyOTY4ODQsImV4cCI6MjA1ODg3Mjg4NH0.NpiCWySbD58ANDGLukvqiGNN7e_pHxRxAsxHCI7QWAE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);